import Head from "next/head";
import Image from "next/image";
import { Text } from "react-native";
import * as Tooltip from "universal-tooltip";

import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Tooltip.Root>
          <Tooltip.Trigger>
            <div className={styles.center}>
              <Image
                className={styles.logo}
                src="/next.svg"
                alt="Next.js Logo"
                width={180}
                height={37}
                priority
              />
            </div>
          </Tooltip.Trigger>
          <Tooltip.Content>
            <Tooltip.Text text="Tooltip" textColor="#000" />
          </Tooltip.Content>
        </Tooltip.Root>
      </main>
    </>
  );
}
